### ISSUE TITLE
Add support for quadratic objectives

### ISSUE THREAD

**Issue by migarstka** [jump-dev/MosekTools.jl#52]
Atm the MOI interface for Mosek doesn't support quadratic objectives (without bridges). Was that a conscious decision?

Mosek certainly supports quadratic objectives modeling, see this example: 
https://github.com/JuliaOpt/Mosek.jl/blob/master/examples/qo1.jl

or in Python:
https://docs.mosek.com/9.2/pythonapi/tutorial-qo-shared.html

I am assuming here that the problem isn't transformed internally by mosek when a quadratic objective term is added via their model API.

**Comment by blegat** [comment]
> I am assuming here that the problem isn't transformed internally by mosek when a quadratic objective term is added via their model API.

That's a good question. If it indeed does not internally transform it then it would make sense to support it. 
@ulfworsoe?

**Comment by erling-d-andersen** [comment]
Quadratic problems are converted to conic form before they are optimized.

**Comment by blegat** [comment]
In that case, it seems better not to support quadratic objective. Otherwise, when the user use quadratic objective with conic constraints, the bridges won't transform it to SOC because Mosek says it's supported and then it won't work. The second reason is that we prefer not to support what is transformed internally so that the transformation are transparently reported by the bridging and that information can be used by the bridges to determine what is the best reformulation.
